title: "Daniel Friis" # the name of your site, e.g. ACME Corp.
description: ""
lang: en-US # default lang

url: "https://www.danielfriis.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /:collection/:title/

collections:
  posts:
    permalink: /notes/:title/
    output: true
  quotes:
    sort_by: id

defaults:
  - scope:
      type: posts
    values:
      layout: default

plugins:
  - jekyll-postcss-v2
  - jekyll-sitemap

postcss:
  cache: false

jekyll_compose:
    auto_open: true
    default_front_matter:
      drafts:
        description:

include:
  - _pages
  - .htaccess
